[package]
name = "notarium"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.27", default-features = false, features = ["default_fonts", "glow", "x11", "wayland"] }
rodio = { version = "0.17", default-features = false }

[dev-dependencies]
approx = "0.5"
