[package]
name = "notarium"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.33.2"
egui_glium = "0.33.2"
glium = "0.36.0"
rodio = { version = "0.17", default-features = false }

[dev-dependencies]
approx = "0.5"
