[package]
name = "notarium"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.27"
egui_glium = "0.27"
glium = "0.34"
rodio = { version = "0.17", default-features = false }

[dev-dependencies]
approx = "0.5"
